### ISSUE TITLE
Using in Craft Module

### ISSUE THREAD

**Issue by DigitalRebelMarketing** [nystudio107/craft-connect#27]
What is the best practice (code) of connecting via a module I built in Craft using PHP?

**Comment by DigitalRebelMarketing** [comment]
I got it working using the following... is this the correct way to query in PHP?
```
        $connect = new ConnectVariable;
        $data = $connect->open('data');
        $query = $connect->query($data)->select('email')->from('tco')->all();
```

**Comment by khalwat** [comment]
If you're in PHP-land you don't really need the plugin at all but... sure, that's one way.
