### ISSUE TITLE
Working example of using createCommand with craft-connect?

### ISSUE THREAD

**Issue by Geestig** [nystudio107/craft-connect#3]
Hi.
First, thanks for this great plugin! However I seem to be unable to actually use the createCommand function. I'm trying to do a simple INSERT INTO but can't get it to work.

The error i'm receiving is the following: "Call to a member function getQueryBuilder() on string"

```
{% set db = craft.connect.open('remote') %}
{% set sql = 'INSERT INTO tblContact_Management (city, email, lang, lastname) VALUES (citytest, mailtest, nl, De La Phantoma)' %}
{% set projectResults = craft.connect.query(db)
  .createCommand(sql)
%}
```

Here's my actual code for trying to insert something. I have no issues on retrieving data though.

**Comment by khalwat** [comment]
So Connect returns a Query object from `.query()`: https://github.com/nystudio107/craft-connect/blob/v1/src/variables/ConnectVariable.php#L63

But it returns a Connection object from `.open()`: https://github.com/nystudio107/craft-connect/blob/v1/src/variables/ConnectVariable.php#L39

So you can do `{% do db.createCommand(sql) %}`

See also: https://nystudio107.com/blog/cutting-the-cord-removing-plugins#plugin-4-connect

**Comment by Geestig** [comment]
Worked like a charm, thanks for the reply!
