### ISSUE TITLE
Craft-connect plugin documentation info missmatch

### ISSUE THREAD

**Issue by andreibrindas** [nystudio107/craft-connect#42]
### Describe the bug
On the plugin documentation repo, it says it's compatible with Craft CMS version 3.x.x, but when you go ahead and install the plugin, Craft CMS 4.x.x is required. 

### To reproduce
Steps to reproduce the behaviour:
1. Have a Craft CMS install on 3.x.x
2. Run the composer require install
3. See the error 

### Expected behaviour
The docs should have different composer commands for the compatible Craft CMS versions

### Versions
- Plugin version: latest
- Craft version: 3.x.x

**Comment by khalwat** [comment]
If you change the version to `^1.0.0` you will get the Craft 3 compatible version of the plugin.
